#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.3 on Fri Jun 14 21:01:29 2019
#

import wx


# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class frameZnamky(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: frameZnamky.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((450, 350))
        self.SetMinClientSize((450, 350))
        self.tree_ctrl_1 = wx.TreeCtrl(self, wx.ID_ANY)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: frameZnamky.__set_properties
        self.SetTitle("Známky")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: frameZnamky.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(self.tree_ctrl_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade


# end of class frameZnamky

class appZnamky(wx.App):
    def OnInit(self):
        self.frameZnamky = frameZnamky(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frameZnamky)
        self.frameZnamky.Show()
        return True

# end of class appZnamky
