#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.3 on Thu May 30 06:22:04 2019
#

import wx
import wx.adv
import wx.grid


# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class frameRozvrh(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: frameRozvrh.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((640, 480))
        self.statusbar = self.CreateStatusBar(1)
        self.buttonPrev = wx.Button(self, wx.ID_ANY, "<<")
        self.dateWeek = wx.adv.DatePickerCtrl(self, wx.ID_ANY, style=wx.adv.DP_DEFAULT)
        self.buttonNext = wx.Button(self, wx.ID_ANY, ">>")
        self.RozvrhGrid = wx.grid.Grid(self, wx.ID_ANY, size=(1, 1))
        self.buttonChangeUser = wx.Button(self, wx.ID_ANY, u"Změnit uživatele")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: frameRozvrh.__set_properties
        self.SetTitle("Rozvrh hodin")
        self.statusbar.SetStatusWidths([-1])

        # statusbar fields
        statusbar_fields = [u"Aktuální týden"]
        for i in range(len(statusbar_fields)):
            self.statusbar.SetStatusText(statusbar_fields[i], i)
        self.dateWeek.Enable(False)
        self.RozvrhGrid.CreateGrid(0, 0)
        self.RozvrhGrid.EnableEditing(0)
        self.RozvrhGrid.EnableDragColSize(0)
        self.RozvrhGrid.EnableDragRowSize(0)
        self.RozvrhGrid.EnableDragGridSize(0)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: frameRozvrh.__do_layout
        Sizer = wx.GridBagSizer(0, 0)
        Sizer.Add(self.buttonPrev, (0, 0), (1, 1), wx.ALIGN_CENTER | wx.ALL | wx.EXPAND, 10)
        Sizer.Add(self.dateWeek, (0, 1), (1, 1), wx.ALIGN_CENTER | wx.ALL | wx.EXPAND, 10)
        Sizer.Add(self.buttonNext, (0, 2), (1, 1), wx.ALIGN_CENTER | wx.ALL | wx.EXPAND, 10)
        Sizer.Add(self.RozvrhGrid, (1, 0), (1, 3), wx.ALIGN_CENTER | wx.ALL | wx.EXPAND, 10)
        Sizer.Add(self.buttonChangeUser, (2, 0), (1, 1), wx.ALL, 10)
        self.SetSizer(Sizer)
        Sizer.AddGrowableRow(1)
        Sizer.AddGrowableCol(0)
        Sizer.AddGrowableCol(1)
        Sizer.AddGrowableCol(2)
        self.Layout()
        # end wxGlade


# end of class frameRozvrh

class dialogLogin(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: dialogLogin.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.textUser = wx.TextCtrl(self, wx.ID_ANY, "")
        self.textPass = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_PASSWORD)
        self.cityComboBox = wx.ComboBox(self, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        self.schoolComboBox = wx.ComboBox(self, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        self.textUrl = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.TE_READONLY)
        self.buttonLogin = wx.Button(self, wx.ID_ANY, u"Přihlásit se")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: dialogLogin.__set_properties
        self.SetTitle("Login")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: dialogLogin.__do_layout
        Sizer = wx.BoxSizer(wx.VERTICAL)
        labelLogin = wx.StaticText(self, wx.ID_ANY, u"Přihlašte se: ")
        Sizer.Add(labelLogin, 0, wx.ALIGN_CENTER | wx.ALL | wx.EXPAND, 10)
        Sizer.Add(self.textUser, 0, wx.ALIGN_CENTER | wx.ALL | wx.EXPAND, 10)
        Sizer.Add(self.textPass, 0, wx.ALIGN_CENTER | wx.ALL | wx.EXPAND, 10)
        Sizer.Add(self.cityComboBox, 0, wx.ALIGN_CENTER | wx.ALL | wx.EXPAND, 10)
        Sizer.Add(self.schoolComboBox, 0, wx.ALIGN_CENTER | wx.ALL | wx.EXPAND, 10)
        Sizer.Add(self.textUrl, 0, wx.ALIGN_CENTER | wx.ALL | wx.EXPAND, 10)
        Sizer.Add(self.buttonLogin, 0, wx.ALIGN_CENTER | wx.ALL | wx.EXPAND, 10)
        self.SetSizer(Sizer)
        Sizer.Fit(self)
        self.Layout()
        # end wxGlade


# end of class dialogLogin

class RozvrhApp(wx.App):
    def OnInit(self):
        self.frameRozvrh = frameRozvrh(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frameRozvrh)
        self.frameRozvrh.Show()
        return True


# end of class RozvrhApp

if __name__ == "__main__":
    RozvrhHodin = RozvrhApp(0)
    RozvrhHodin.MainLoop()
