#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.3 on Tue Sep  3 21:30:57 2019
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class frameGrades(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: frameGrades.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 300))
        self.tree = wx.TreeCtrl(self, wx.ID_ANY)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: frameGrades.__set_properties
        self.SetTitle("frame")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: frameGrades.__do_layout
        sizer = wx.BoxSizer(wx.VERTICAL)
        sizer.Add(self.tree, 1, wx.EXPAND, 0)
        self.SetSizer(sizer)
        self.Layout()
        # end wxGlade

# end of class frameGrades

class appGrades(wx.App):
    def OnInit(self):
        self.frameGrades = frameGrades(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frameGrades)
        self.frameGrades.Show()
        return True

# end of class appGrades
