#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.3 on Tue Sep  3 21:28:38 2019
#

import wx
import wx.grid

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class frameTimetable(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: frameTimetable.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((640, 480))
        self.statusbar = self.CreateStatusBar(1)
        self.buttonPrev = wx.Button(self, wx.ID_ANY, "<<")
        self.buttonNext = wx.Button(self, wx.ID_ANY, ">>")
        self.gridTimetable = wx.grid.Grid(self, wx.ID_ANY, size=(1, 1))

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: frameTimetable.__set_properties
        self.SetTitle("Rozvrh hodin")
        self.statusbar.SetStatusWidths([-1])

        # statusbar fields
        statusbar_fields = [u"Aktuální týden"]
        for i in range(len(statusbar_fields)):
            self.statusbar.SetStatusText(statusbar_fields[i], i)
        self.gridTimetable.CreateGrid(0, 0)
        self.gridTimetable.EnableEditing(0)
        self.gridTimetable.EnableDragColSize(0)
        self.gridTimetable.EnableDragRowSize(0)
        self.gridTimetable.EnableDragGridSize(0)
        self.gridTimetable.SetFocus()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: frameTimetable.__do_layout
        sizer = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_1 = wx.GridBagSizer(0, 0)
        sizer_1.Add(self.buttonPrev, (0, 0), (1, 1), wx.ALIGN_CENTER | wx.ALL | wx.EXPAND, 5)
        sizer_1.Add(self.buttonNext, (0, 1), (1, 1), wx.ALIGN_CENTER | wx.ALL | wx.EXPAND, 5)
        sizer_1.AddGrowableCol(0)
        sizer_1.AddGrowableCol(1)
        sizer.Add(sizer_1, 0, wx.ALIGN_CENTER | wx.ALL | wx.EXPAND, 10)
        sizer_2.Add(self.gridTimetable, 0, wx.ALIGN_CENTER | wx.ALL | wx.EXPAND, 5)
        sizer.Add(sizer_2, 0, wx.ALIGN_CENTER | wx.ALL | wx.EXPAND, 10)
        self.SetSizer(sizer)
        self.Layout()
        # end wxGlade

# end of class frameTimetable

class appTimetable(wx.App):
    def OnInit(self):
        self.frameTimetable = frameTimetable(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frameTimetable)
        self.frameTimetable.Show()
        return True

# end of class appTimetable
